=== WilldelaVega777/Producer/ProducerASPX/Specs/WebShowSpec.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 (http://www.altova.com) by William Vega (DimSoft) -->
<!--W3C Schema generated by XMLSpy v2007 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="WebSlides">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="WebSlide" maxOccurs="9999"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="WebSlide">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Thumbnail"/>
				<xs:element ref="Assets"/>
				<xs:element ref="OverLink" minOccurs="0"/>
				<xs:element ref="PageLink" minOccurs="0"/>
				<xs:element ref="ConversationalPoll" minOccurs="0"/>
				<xs:element ref="SurfMenu" minOccurs="0"/>
				<xs:element ref="WatchClip" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="WebSlideFrameLoopColor" type="xs:string"/>
			<xs:attribute name="WebSlideFrameLoopOpacity" type="xs:double"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="WebShowManifest">
		<xs:annotation>
			<xs:documentation>xmlns??</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="WebSlides"/>
			</xs:sequence>
			<xs:attribute name="WebShowVersion" type="xs:string" use="required"/>
			<xs:attribute name="WebShowName" type="xs:string" use="required"/>
			<xs:attribute name="WebShowDate" type="xs:string" use="required"/>
			<xs:attribute name="WebShowAuthor" type="xs:string" use="required"/>
			<xs:attribute name="InitialVideoWindowY" type="xs:double" use="required"/>
			<xs:attribute name="InitialVideoWindowX" type="xs:double" use="required"/>
			<xs:attribute name="InitialVideoWindowWidth" type="xs:double" use="required"/>
			<xs:attribute name="InitialVideoWindowHeight" type="xs:double" use="required"/>
			<xs:attribute name="InitialVideoWindowSource" type="xs:string" use="required"/>
			<xs:attribute name="BasePath" type="xs:string" use="required"/>
			<xs:attribute name="BottomBarDefaultColor" type="xs:string" use="required"/>
			<xs:attribute name="BottomBarDefaultOpacity" type="xs:double" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Thumbnail">
		<xs:complexType>
			<xs:attribute name="ImageSource" type="xs:string" use="required"/>
			<xs:attribute name="FrameText" type="xs:string" use="required"/>
			<xs:attribute name="FrameID" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="PageLink">
		<xs:complexType>
			<xs:attribute name="Top" type="xs:double" use="required"/>
			<xs:attribute name="Left" type="xs:double" use="required"/>
			<xs:attribute name="InitialButtonDelayTime" type="xs:string" use="required"/>
			<xs:attribute name="Url" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Assets">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Asset" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Asset">
		<xs:complexType>
			<xs:attribute name="ID" type="xs:string" use="required"/>		
			<xs:attribute name="Value" type="xs:string" use="required"/>		
		</xs:complexType>
	</xs:element>
	<xs:element name="ConversationalPoll">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Questions">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Question" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="EndMessage" type="xs:string" use="required"/>
			<xs:attribute name="DefaultFontSize" type="xs:double" use="required"/>
			<xs:attribute name="DefaultAnswerMargin" type="xs:double" use="required"/>
			<xs:attribute name="DefaultQuestionMargin" type="xs:double" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Question">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="QuestionTexts">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="QuestionText" maxOccurs="5"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Answers">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Answer" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Id" type="xs:int" use="required"/>
			<xs:attribute name="FontSize" type="xs:double"/>
			<xs:attribute name="QuestionMargin" type="xs:double"/>
			<xs:attribute name="AnswerMargin" type="xs:double"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="QuestionText">
		<xs:complexType>
			<xs:attribute name="Text" use="required"/>
			<xs:attribute name="Order" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Answer">
		<xs:complexType>
			<xs:attribute name="Id" type="xs:int" use="required"/>
			<xs:attribute name="Text" type="xs:string" use="required"/>
			<xs:attribute name="NextQuestionID" type="xs:integer"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Interfaces">
		<xs:complexType>
			<xs:sequence/>
		</xs:complexType>
	</xs:element>
	<xs:element name="OverLink">
		<xs:complexType>
			<xs:attribute name="Top" type="xs:double" use="required"/>
			<xs:attribute name="Left" type="xs:double" use="required"/>
			<xs:attribute name="InitialButtonDelayTime" type="xs:string" use="required"/>
			<xs:attribute name="Url" type="xs:string" use="required"/>
			<xs:attribute name="Duration" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SurfMenu">
		<xs:complexType>
			<xs:attribute name="Left" type="xs:double" use="required"/>
			<xs:attribute name="Top" type="xs:double" use="required"/>
			<xs:attribute name="Resource" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="WatchClip">
		<xs:complexType>
			<xs:attribute name="Left" type="xs:double" use="required"/>
			<xs:attribute name="Top" type="xs:double" use="required"/>
			<xs:attribute name="VideoClip" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== WilldelaVega777/Producer/ProducerASPX/WebShows/0000000004/Manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<WebShowManifest xsi:noNamespaceSchemaLocation="..\..\Specs\WebShowSpec.xsd" WebShowName="Project270" WebShowAuthor="Carl Carpenter" WebShowDate="3/26/2009 3:41:02 PM" WebShowVersion="3" InitialVideoWindowX="760" InitialVideoWindowY="17" InitialVideoWindowHeight="160" InitialVideoWindowWidth="140" InitialVideoWindowSource="/WebShows/0000000000/Resources/WebShowVideo.wmv" BasePath="/WebShows/0000000000/" BottomBarDefaultColor="#aa000000" BottomBarDefaultOpacity="0.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <WebSlides>
    <WebSlide>
      <Thumbnail FrameID="1" ImageSource="/WebShows/0000000000/Resources/Thumbnails/Default.jpg" FrameText="New Webslide" />
      <Assets>
        <Asset ID="OMovingBackground" Value="WebSlideBackground_1.jpg" />
      </Assets>
    </WebSlide>
    <WebSlide>
      <Thumbnail FrameID="2" ImageSource="/WebShows/0000000000/Resources/Thumbnails/Default.jpg" FrameText="New Webslide" />
      <Assets>
        <Asset ID="OMovingBackground" Value="WebSlideBackground_2.jpg" />
      </Assets>
    </WebSlide>
    <WebSlide>
      <Thumbnail FrameID="3" ImageSource="/WebShows/0000000000/Resources/Thumbnails/Default.jpg" FrameText="New VideoFrame" />
      <Assets>
        <Asset ID="OMovingBackground" Value="WebSlideBackground_3.jpg" />
      </Assets>
    </WebSlide>
    <WebSlide>
      <Thumbnail FrameID="4" ImageSource="/WebShows/0000000000/Resources/Thumbnails/Default.jpg" FrameText="New Webslide" />
      <Assets>
        <Asset ID="OMovingBackground" Value="WebSlideBackground_4.jpg" />
      </Assets>
    </WebSlide>
    <WebSlide>
      <Thumbnail FrameID="5" ImageSource="/WebShows/0000000000/Resources/Thumbnails/Default.jpg" FrameText="New Webslide" />
      <Assets>
        <Asset ID="OMovingBackground" Value="WebSlideBackground_5.jpg" />
      </Assets>
    </WebSlide>
  </WebSlides>
</WebShowManifest>

=== WilldelaVega777/Producer/ProducerASPX/WebShows/0000000002/Manifest.xml
<?xml version="1.0" encoding="utf-8"?>
<WebShowManifest  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\Specs\WebShowSpec.xsd" 
                  WebShowName="OC Register Webshow News" 
                  WebShowAuthor="Carl Carpenter" 
                  WebShowDate="10/14/2008" 
                  WebShowVersion="1.0" 
                  InitialVideoWindowX="760" 
                  InitialVideoWindowY="17" 
                  InitialVideoWindowWidth="140" 
                  InitialVideoWindowHeight="160" 
                  InitialVideoWindowSource="/WebShows/0000000002/Resources/WebShowVideo.wmv" 
                  BasePath="/WebShows/0000000002/" 
                  BottomBarDefaultColor="#cc000000"
                  BottomBarDefaultOpacity=".4">
	<WebSlides>

    <WebSlide>
      <Thumbnail FrameID="001" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Welcome"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide1.jpg"/>        
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="002" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="The scene"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide2.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
			<Thumbnail FrameID="003" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="The evidence"/>
			<Assets>
        <Asset ID="OMovingBackground" Value="Webslide3.jpg"/>
      </Assets>
		</WebSlide>
	
		<WebSlide>
			<Thumbnail FrameID="004" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Arrest"/>
			<Assets>
        <Asset ID="OMovingBackground" Value="Webslide4.jpg"/>
      </Assets>
		</WebSlide>    
      
		<WebSlide>
			<Thumbnail FrameID="005" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Investigation"/>
			<Assets>
        <Asset ID="OMovingBackground" Value="Webslide5.jpg"/>
      </Assets>
		</WebSlide>
	
		<WebSlide>
			<Thumbnail FrameID="006" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Article"/>
			<Assets>
        <Asset ID="OMovingBackground" Value="Webslide6.jpg"/>
      </Assets>
      <PageLink Url="http://www.ocregister.com/articles/girl-palma-martinez-2177219-vehicle-intersection" InitialButtonDelayTime="00:00:04" Top="376" Left="-26" />
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="007" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Double tragedy"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide7.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
     <Thumbnail FrameID="008" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Car show"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide8.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="009" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Infinity"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide9.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="010" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Clean diesel"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide10.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="011" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Hybrids"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide11.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="012" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Audi"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide12.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
			<Thumbnail FrameID="013" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Tiguan"/>
			<Assets>
        <Asset ID="OMovingBackground" Value="Webslide13.jpg"/>
      </Assets>
		</WebSlide>

    <WebSlide>
      <Thumbnail FrameID="014" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Solstice"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide14.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="015" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Rolls"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide15.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="016" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Big fan"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide16.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="017" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Bay"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide17.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="018" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Youkilis"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide18.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="019" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Home run"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide19.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="020" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Garret scores"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide20.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="021" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Lackey"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide21.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="022" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Relieved"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide22.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="023" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Lowrie scores"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide23.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="024" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Fenway"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide24.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="025" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Poll"/>
      <Assets>
        <Asset ID="OBackground" Value="Webslide25.jpg"/>
      </Assets>
      <ConversationalPoll DefaultFontSize="18" EndMessage="Thanks!" DefaultQuestionMargin="300" DefaultAnswerMargin="90">
        <Questions>
          <Question Id="1">
            <QuestionTexts>
              <QuestionText Text="Whatâ€™s the single most important thing the Angels need to change before Game 2?" Order="1"></QuestionText>
            </QuestionTexts>
            <Answers>
              <Answer Id="1" Text="Generate some offensive firepower"></Answer>
              <Answer Id="2" Text="Shake up the lineup"></Answer>
              <Answer Id="3" Text="Go to the bullpen faster"></Answer>
              <Answer Id="4" Text="Run more"></Answer>
              <Answer Id="5" Text="Argue more with the umpires"></Answer>
              <Answer Id="6" Text="Play someone other than Boston"></Answer>
            </Answers>
          </Question>
        </Questions>
      </ConversationalPoll>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="026" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Angels article"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide26.jpg"/>
      </Assets>
      <PageLink Url="http://www.ocregister.com/articles/third-angels-one-2176958-game-base" InitialButtonDelayTime="00:00:02" Top="376" Left="-26" />
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="027" ImageSource="/WebShows/0000000002/Resources/Thumbnails/Default.jpg" FrameText="Close"/>
      <Assets>
        <Asset ID="OMovingBackground" Value="Webslide27.jpg"/>
      </Assets>
    </WebSlide>

  </WebSlides>
</WebShowManifest>

=== WilldelaVega777/Producer/ProducerASPX/WebShows/0000000001/Manifest.xml
<?xml version="1.0" encoding="utf-8"?>
<WebShowManifest  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\Specs\WebShowSpec.xsd" 
                  WebShowName="The Most Inconvenient Truth" 
                  WebShowAuthor="Carl Carpenter" 
                  WebShowDate="11/22/2007" 
                  WebShowVersion="2.0" 
                  InitialVideoWindowX="760" 
                  InitialVideoWindowY="17" 
                  InitialVideoWindowWidth="140" 
                  InitialVideoWindowHeight="160" 
                  InitialVideoWindowSource="/WebShows/0000000001/Resources/WebShowVideo.wmv" 
                  BasePath="/WebShows/0000000001/" 
                  BottomBarDefaultColor="#cc000000"
                  BottomBarDefaultOpacity=".4">
	<WebSlides>

    <WebSlide>
      <Thumbnail FrameID="001" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="Behold"/>
      <Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="Webslide1.jpg"/>        
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="002" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="Laying waste"/>
      <Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="Webslide2.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
			<Thumbnail FrameID="003" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="Agent Smith"/>
			<Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="Webslide3.jpg"/>
        <Asset ID="QuoteText" Value="Quotetext.png"/>
      </Assets>
      <SurfMenu Left="-43" Top="239" Resource="WayvSL2.Components.Skins.SurfMenu.SurfMenuWebslide3.xaml"/>
      <WatchClip Left="4" Top="466" VideoClip="/WebShows/0000000001/Resources/WatchClips/Matrix.wmv"/>
		</WebSlide>
	
		<WebSlide>
			<Thumbnail FrameID="004" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="A Virus"/>
			<Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="Webslide4.jpg"/>
      </Assets>
		</WebSlide>    
      
		<WebSlide>
			<Thumbnail FrameID="005" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="Global self"/>
			<Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="Webslide5.jpg"/>
        <Asset ID="GlobalSelfTextOverlay" Value="GlobalSelfText.png"/>
        <Asset ID="BinaryMatrixTextOverlay" Value="BinaryMatrix.png"/>
      </Assets>
		</WebSlide>
	
		<WebSlide>
			<Thumbnail FrameID="006" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="Barely conscious"/>
			<Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="VideoFrame06.wmv"/>
      </Assets>
		</WebSlide>

    <WebSlide>
      <Thumbnail FrameID="007" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="James Lovelock"/>
      <Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="Webslide7.jpg"/>
        <Asset ID="QuoteText" Value="QuoteText.png"/>
        <Asset ID="GaiaText" Value="GaiaText.png"/>
        <Asset ID="GaiaText2" Value="GaiaText2.png"/>
      </Assets>
      <SurfMenu Left="-43" Top="300" Resource="WayvSL2.Components.Skins.SurfMenu.SurfMenuWebslide7.xaml"/>
    </WebSlide>

    <WebSlide>
     <Thumbnail FrameID="008" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="Tipping Point"/>
      <Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="Webslide8.jpg"/>
        <Asset ID="PastTippingPointText" Value="PastTippingPointText.png"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="009" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="Gone"/>
      <Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="Webslide9.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="010" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="Biocide"/>
      <Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="Webslide10.jpg"/>
      </Assets>
      <SurfMenu Left="-43" Top="410" Resource="WayvSL2.Components.Skins.SurfMenu.SurfMenuWebslide10.xaml"/>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="011" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="Amphibians"/>
      <Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="Webslide11.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="012" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="70 species gone"/>
      <Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="Webslide12.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
			<Thumbnail FrameID="013" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="Independent Report"/>
			<Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="Webslide13.jpg"/>
        <Asset ID="QuotePane" Value="QuotePane.png"/>
      </Assets>
			<PageLink Url="http://www.independent.co.uk/environment/article2494659.ece" InitialButtonDelayTime="00:00:07" Top="376" Left="-26" />
		</WebSlide>

    <WebSlide>
      <Thumbnail FrameID="014" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="Mass Extinction"/>
      <Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="Webslide14.jpg"/>
        <Asset ID="EXTINCTION" Value="EXTINCTION.png"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="015" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="Carnivores 1"/>
      <Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="Webslide15.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="016" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="Carnivores 2"/>
      <Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="Webslide16.jpg"/>
      </Assets>
      <SurfMenu Left="-25" Top="410" Resource="WayvSL2.Components.Skins.SurfMenu.SurfMenuWebslide16.xaml"/>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="017" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="Herbivores"/>
      <Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="Webslide17.jpg"/>
      </Assets>
    </WebSlide>

    <WebSlide>
      <Thumbnail FrameID="018" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="Human Brain"/>
      <Assets>
        <Asset ID="OBackground" Value="Null.jpg"/>
        <Asset ID="OMovingBackground" Value="Webslide18.jpg"/>
        <Asset ID="SaberTooth" Value="SaberToothSpecter.png"/>
      </Assets>
    </WebSlide>   
	
		<WebSlide>
			<Thumbnail FrameID="019" ImageSource="/WebShows/0000000001/Resources/Thumbnails/Default.jpg" FrameText="Conversational Poll"/>
			<Assets>
				<Asset ID="OBackground" Value="Webslide19.jpg"/>
			</Assets>
			<ConversationalPoll DefaultFontSize="20" EndMessage="Thanks for participating" DefaultQuestionMargin="300" DefaultAnswerMargin="90">
				<Questions>
				  <Question Id="1">
					<QuestionTexts>
					  <QuestionText Text="Were you aware of the Sixth Mass Extinction... and that we humans are causing it?" Order="1"></QuestionText>
					</QuestionTexts>
					<Answers>
					  <Answer Id="1" NextQuestionID="3" Text="Yes"></Answer>
					  <Answer Id="2" NextQuestionID="2" Text="No"></Answer>
					</Answers>
				  </Question>
				  <Question Id="2">
					<QuestionTexts>
					  <QuestionText Text="Now that you are, would you be willing to help in some way to stop it?" Order="1"></QuestionText>
					</QuestionTexts>
					<Answers>
					  <Answer Id="1" Text="Yes"></Answer>
					  <Answer Id="2" Text="No"></Answer>
					  <Answer Id="3" Text="Maybe"></Answer>
					</Answers>
				  </Question>
				  <Question Id="3">
					<QuestionTexts>
					  <QuestionText Text="Are you doing anything at this point to help stop it?" Order="1"></QuestionText>
					</QuestionTexts>
					<Answers>
					  <Answer Id="1" Text="Yes"></Answer>
					  <Answer Id="2" NextQuestionID="4" Text="No"></Answer>
					</Answers>
				  </Question>
				  <Question Id="4">
					<QuestionTexts>
					  <QuestionText Text="Would you be willing to help if you thought you could?" Order="1"></QuestionText>
					</QuestionTexts>
					<Answers>
					  <Answer Id="1" Text="Yes"></Answer>
					  <Answer Id="2" Text="No"></Answer>
					  <Answer Id="3" Text="Maybe"></Answer>
					</Answers>
				  </Question>
				</Questions>
			</ConversationalPoll>
		</WebSlide>  
  </WebSlides>
</WebShowManifest>
